# 文件下载配置
download:
  # 默认下载目录
  default_download_dir: "comment"

  # 超时设置（秒）
  timeout: 30
  
  # 重试次数
  max_retries: 3
  
  # 块大小（字节）用于分块下载
  chunk_size: 8192
  
  # 用户代理
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  
  # 是否验证SSL证书
  verify_ssl: true
  
  # 支持的文件类型（可选，为空则下载所有类型）
  allowed_extensions: 
    - ".zip"
  
  # 文件大小限制（MB，0表示无限制）
  max_file_size_mb: 0

# 下载任务列表示例
download_tasks:
  - url: "http://chalaoshi.click/static/download/chalaoshi_csv20250502_5399305_2696_26893D_sha256.zip"
    filename: ""  # 如果为空，将使用URL中的文件名
    download_dir: "comment"

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "logs/download.log"
  log_format: "%(asctime)s - %(levelname)s - %(message)s"
