# 文件解压配置
extract:
  # 默认解压目录
  default_extract_dir: "comment/extracted"
  
  # 是否保留原始压缩文件
  keep_archive: true
  
  # 是否覆盖已存在的文件
  overwrite_existing: false
  
  # 支持的压缩文件类型
  supported_formats:
    - ".zip"
  
  # 解压时的编码（处理中文文件名）
  encoding: "utf-8"

# 密码配置
passwords:
  # 默认密码列表（按优先级排序）
  default_passwords:
    - ""
  
  # 特定文件的密码映射
  file_passwords:
    "chalaoshi_csv20250502_5399305_2696_26893D_sha256.zip": 
      - type: "raw"
        content: "切勿交浅言深。不要干涉他人因果。牢记八个字：关我屁事。关你屁事。"

# 解压任务列表
extract_tasks:
  - archive_path: "comment/chalaoshi_csv20250502_5399305_2696_26893D_sha256.zip"
    extract_dir: "comment/extracted"
    password: ""  # 如果为空，将尝试配置中的密码列表

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "logs/extract.log"
  log_format: "%(asctime)s - %(levelname)s - %(message)s"
